---
timezone: America/New_York
title: Erick Peirson
description: "Describe"

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: pygments
excerpt_separator: <!--more-->
paginate: 5

kramdown:
  input: GFM
---
